jobs:

- job: CodeQuality
  pool:
    vmImage: 'ubuntu-18.04'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'npm ci'

  - script: npm run static-code-analysis
    displayName: 'npm run static-code-analysis'

  - script: npm run dynamic-code-analysis
    displayName: 'npm run dynamic-code-analysis'

- job: Android
  dependsOn: CodeQuality
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'npm ci'

  - task: Gradle@2
    displayName: 'Building Android apk (debug)...'
    inputs:
      workingDirectory: 'android/'
      gradleWrapperFile: 'android/gradlew'
      gradleOptions: '-Xmx3072m'
      publishJUnitResults: false
      testResultsFiles: '**/TEST-*.xml'
      tasks: 'assembleDebug'

  - task: CopyFiles@2
    displayName: 'Copying .apk files...'
    inputs:
      contents: '**/*.apk'
      targetFolder: '$(build.artifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'Archiving .apk...'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)/android/app/build/outputs/apk/'
      artifactName: 'apk'
      artifactType: 'container'

- job: iOS
  dependsOn: CodeQuality
  pool:
    vmImage: 'macOS-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'
    displayName: 'Install Node.js'

  - script: npm ci
    displayName: 'npm ci'

  - task: CocoaPods@0
    inputs:
      workingDirectory: 'ios/'

  - task: Xcode@5
    displayName: 'Building iOS app (debug)...'
    inputs:
      actions: 'clean build archive'
      sdk: 'iphoneos'
      configuration: 'Debug'
      xcWorkspacePath: 'ios/HelloReactNative.xcworkspace'
      scheme: 'HelloReactNative'
      xcodeVersion: '10'
      signingOption: 'nosign'
      useXcpretty: 'false'
      exportPath: '$(agent.buildDirectory)/output/$(sdk)/$(configuration)'
      packageApp: false
      args: '-UseModernBuildSystem=NO -archivePath $(agent.buildDirectory)/HelloReactNative'

  - task: ArchiveFiles@2
    displayName: 'Compressing .xcarchive directory into a zip file'
    inputs:
      rootFolderOrFile: '$(agent.buildDirectory)/HelloReactNative.xcarchive/'
      archiveFile: '$(build.artifactStagingDirectory)/HelloReactNative.xcarchive.zip'

  - task: PublishBuildArtifacts@1
    displayName: 'Archiving .xcarchive...'
    inputs:
      pathToPublish: '$(build.artifactStagingDirectory)/HelloReactNative.xcarchive.zip'
      artifactName: 'xcarchive'
      artifactType: 'container'

